### ISSUE TITLE
State/stage output

### ISSUE THREAD

**Issue by coinop-logan** [cryptoprimitive/crowdserve-debut#1]

**Comment by coinop-logan** [comment]
Method that uses the local fetched info to return one of the following strings: "Active (Preview)", "Active", "Ending", "Inactive"

**Comment by gianlucaschoefer** [comment]
has been implemented in crowdserve_api.js
I'm not closing this issue yet, because I'm proposing to implemented this in the "getFullState" method directly, and return the string as fullState.state 
@coinop-logan please advise

**Comment by gianlucaschoefer** [comment]
I'll leave this as before and close

**Comment by coinop-logan** [comment]
Sorry for the late response--I like your idea of supplying the state string as part of the returned fullState object. Please implement as you have described.

**Comment by gianlucaschoefer** [comment]
integrated.
