### ISSUE TITLE
Methods to contribute, transfer, and recall

### ISSUE THREAD

**Issue by coinop-logan** [cryptoprimitive/crowdserve-debut#5]

**Comment by gianlucaschoefer** [comment]
@coinop-logan in the contract "transfer" uses a data as a paramter. how should this be handled? my idea would be to use a string in javascript and convert it to hex?

**Comment by coinop-logan** [comment]
There are two transfer functions; the one that takes a data parameter is
part of the ERC223 spec. Our api only needs to use the simpler version of
transfer, for now.

**Comment by gianlucaschoefer** [comment]
Ok, done.
