### ISSUE TITLE
Method to return or populate list with all events

### ISSUE THREAD

**Issue by coinop-logan** [cryptoprimitive/crowdserve-debut#7]

**Comment by coinop-logan** [comment]
This method should return just the event types and their arguments; formatting and alignment will be handled higher up on the stack.

**Comment by gianlucaschoefer** [comment]
Added all functions to query all events separately by event name (one function for RoundBegun, one function for RoundEnden, etc.). @coinop-logan is this issue still relevant? Seems to be unecessary complicated to implement, as I have to either transform the raw arguments from hex or call every single event function seperately and combine the outputs.

**Comment by coinop-logan** [comment]
You can use the allEvents function:
https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-allevents

On Sun, Feb 18, 2018 at 7:17 PM, Gianluca Schoefer <notifications@github.com

**Comment by coinop-logan** [comment]
(This is how Toastycoin currently builds the history for the interact page)

**Comment by gianlucaschoefer** [comment]
Yes i already found this, I thought I had deleted my comment..

**Comment by coinop-logan** [comment]
Ah I think you did, but then I responded by email--only to be confused that
I couldn't find the actual message on github.

**Comment by gianlucaschoefer** [comment]
yep, anyway thanks. also, implemented.
